### ISSUE TITLE
network storage lead to error when pushing

### ISSUE THREAD

**Issue by Grwmagad** [atSCM/atscm#289]
Dear all,

I am using a Mac and a VirtualMachine with Windows on which all the atscm and atvise stuff is running.
All the data is laying on the mac and windows has access over network, as VMWare is usually doing this.
So I try to run atscm on a network device.

Problem is when pushing back the source into the atvise project I always get errors like following:

`[13:44:52] Error: [MappingTransformer] Missing reference file, .OperatorList.var.string.array.json should exist (in SYSTEM\GLOBALS\OperatorList.var.string.array)
    at MappingTransformer.transformFromFilesystem (X:\webMI\node_modules\atscm\out\transform\Mapping.js:161:18)
    at MappingTransformer._transform (X:\webMI\node_modules\atscm\out\lib\transform\Transformer.js:146:12)
    at MappingTransformer.Transform._read (X:\webMI\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at MappingTransformer.Transform._write (X:\webMI\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (X:\webMI\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (X:\webMI\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at MappingTransformer.Writable.write (X:\webMI\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (X:\webMI\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)`

You see X: is the network storage. If I do exactly the same but on the windows drive everything goes well. Problem is, that I need the files on Mac and Mac has no access to the windows drive so I need to copy the files. No problem with a little script etc.
I have had a look at the .js files but I think you guys are way faster at looking for the problem here.

Am I the only one with this issue? Is there maybe another problem I didn't think of that leads to such an issue?

Kind regards
Nico

**Comment by Grwmagad** [comment]
Oh, you are right. Thanks for moving this.

**Comment by LukasHechenberger** [comment]
Well, you're setup is exactly mine, though I'm using Parallels for my windows vm. So in general, this should work fine, I'll try to reproduce this issue on my machine.
First of all, just in case I don't get it, is there a specific reason for not simply running atscm on your mac? It's way faster than doing the same over a network drive...

**Comment by Grwmagad** [comment]
Good idea. Never thought of that. I'll give it a try, it doesn't matter to me where atscm is running.

**Comment by LukasHechenberger** [comment]
I'd say, as long as there is no use case where atscm is required to work with network drives I'll close this for now. Feel free to reopen this issue if you've got one.
