### ISSUE TITLE
Pull fails: Node has no data type

### ISSUE THREAD

**Issue by LukasHechenberger** [atSCM/atscm#424]
Originally reported by a user. It seems like an issue with brackets in script names...

```
lukas@Lukass-MacBook-Pro atscm-no-data-type % atscm push
[20:09:37] Using gulpfile ~/Downloads/tmp/atscm-no-data-type/node_modules/atscm/out/Gulpfile.js
[20:09:37] Starting 'push'...
[20:09:38] 'push' errored after 132 ms
[20:09:38] Error: SYSTEM.LIBRARY.PROJECT.MENUSCRIPTS.Synchronize Panels [Users and groups].Synchronize Panels [Users and groups].js has no data type
    at FileNode.get variantValue [as variantValue] (/Users/lukas/Downloads/tmp/atscm-no-data-type/node_modules/atscm/out/lib/gulp/src.js:129:15)
    at SourceBrowser.handleNode [as _nodeHandler] (/Users/lukas/Downloads/tmp/atscm-no-data-type/node_modules/atscm/out/tasks/push.js:173:64)
    at async run (/Users/lukas/Downloads/tmp/atscm-no-data-type/node_modules/p-queue/dist/index.js:163:29)
lukas@Lukass-MacBook-Pro atscm-no-data-type % 
```

**Comment by LukasHechenberger** [comment]
Fix released in version *1.1.1* 👍

Run `atscm update` or `npm install atscm@latest` to update, afterwards `atscm push` should work as expected
