### ISSUE TITLE
Problems pushing display sort order nodes

### ISSUE THREAD

**Issue by LukasHechenberger** [atSCM/atscm#64]
If you set a display sort order in *atvise builder*, a *SortOrder* node is created in the current display folder. Trying to push this node results in a runtime error.

**Steps to reproduce error**

 - Set a display order in a folder in *atvise builder*
 - Run `atscm pull`
 - Run `atscm push`

**Original error message**

```
C:\Users\zz_malr\Downloads\test-atscm>atscm push
[09:04:33] Using gulpfile ~\Downloads\test-atscm\node_modules\atscm\out\Gulpfile.js
[09:04:34] Starting 'push'...
[09:04:42] 'push' errored after 8.95 s
[09:04:42] Error: Error writing ns=1;s=AGENT.DISPLAYS.MAIN.SortOrder: _socket has been disconnected by third party
    at processChunk (C:\Users\zz_malr\Downloads\test-atscm\node_modules\atscm\out\lib\server\QueueStream.js:181:28)
    at session.writeSingleNode (C:\Users\zz_malr\Downloads\test-atscm\node_modules\atscm\out\lib\server\WriteStream.js:50:11)
    at C:\Users\zz_malr\Downloads\test-atscm\node_modules\node-opcua\lib\client\client_session.js:434:20
    at C:\Users\zz_malr\Downloads\test-atscm\node_modules\node-opcua\lib\client\client_session.js:394:20
    at C:\Users\zz_malr\Downloads\test-atscm\node_modules\node-opcua\lib\client\client_session.js:882:20
    at modified_callback (C:\Users\zz_malr\Downloads\test-atscm\node_modules\node-opcua\lib\client\client_secure_channel_layer.js:942:24)
    at process_request_callback (C:\Users\zz_malr\Downloads\test-atscm\node_modules\node-opcua\lib\client\client_secure_channel_layer.js:75:5)
    at C:\Users\zz_malr\Downloads\test-atscm\node_modules\node-opcua\lib\client\client_secure_channel_layer.js:342:9
    at Array.forEach (<anonymous>)
    at ClientSecureChannelLayer._cancel_pending_transactions (C:\Users\zz_malr\Downloads\test-atscm\node_modules\node-opcua\lib\client\client_secure_channel_layer.js:339:37)
```
 
---

<details><summary><strong>Environment</strong></summary>

| package       |               version |
| :------------ | --------------------: |
| OS            | Windows 10 |
| atscm         |         0.3.0 | 
| atscm-cli     |     0.2.2 | 
| atvise server | 3.1.1 |
| node          |          8.4.0 | 
| npm           |           5.3.0 | 
 
</details>

<details><summary><strong>Project configuration</strong></summary>

```javascript
// Atviseproject.babel.js

// default `atscm init` generated Atviseproject.babel.js
```

</details>

**Comment by LukasHechenberger** [comment]
Fixed in #137
